const fs = require("node:fs");
const path = require("node:path");
const { AsyncLocalStorage } = require("node:async_hooks");

const schema = fs.readFileSync(path.join(__dirname, "schema.sql"), "utf8");

// Queries are application-owned SQL; values always travel as bound parameters.
function postgresSql(sql) {
  let index = 0;
  let result = sql.replace(/'(?:''|[^'])*'|\?/g, (token) =>
    token === "?" ? `$${++index}` : token,
  );
  if (/INSERT OR IGNORE INTO/i.test(result)) {
    result =
      result
        .replace(/INSERT OR IGNORE INTO/i, "INSERT INTO")
        .trim()
        .replace(/;$/, "") + " ON CONFLICT DO NOTHING";
  }
  return result
    .replace(/\bBLOB\b/g, "BYTEA")
    .replace(
      /INTEGER PRIMARY KEY AUTOINCREMENT/g,
      "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    )
    .replace(/cleared_before_rowid INTEGER/g, "cleared_before_rowid BIGINT")
    .replace(/MAX\(cleared_before_rowid, /g, "GREATEST(cleared_before_rowid, ");
}

function postgresConfig(connectionString) {
  const url = new URL(connectionString);
  if (!["postgres:", "postgresql:"].includes(url.protocol))
    throw new Error("DATABASE_URL must be a PostgreSQL URL");
  const local = ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname);
  const plain = local && url.searchParams.get("sslmode") === "disable";
  // Never allow URL parameters to silently disable certificate verification.
  for (const key of [
    "sslmode",
    "sslcert",
    "sslkey",
    "sslrootcert",
    "ssl",
    "uselibpqcompat",
  ])
    url.searchParams.delete(key);
  return {
    connectionString: url.toString(),
    ssl: plain ? false : { rejectUnauthorized: true },
    max: 3,
    idleTimeoutMillis: 10000,
    connectionTimeoutMillis: 15000,
    statement_timeout: 15000,
    application_name: "mayak",
  };
}

async function openDatabase({
  url = process.env.DATABASE_URL,
  file = process.env.MAYAK_DB_PATH ||
    path.join(
      process.env.MAYAK_DATA_DIR || path.join(__dirname, ".data"),
      "mayak.sqlite",
    ),
} = {}) {
  const context = new AsyncLocalStorage();
  let pool;
  let sqlite;
  let queue = Promise.resolve();
  const kind = url ? "postgres" : "sqlite";
  const serialize = (callback) => {
    const pending = queue.then(callback, callback);
    queue = pending.catch(() => {});
    return pending;
  };
  if (url) {
    const { Pool } = require("pg");
    const max = Number(process.env.DATABASE_POOL_SIZE || 3);
    if (!Number.isInteger(max) || max < 1 || max > 3)
      throw new Error("DATABASE_POOL_SIZE must be 1..3");
    pool = new Pool({ ...postgresConfig(url), max });
    pool.on("error", () =>
      console.error(
        "Database connection interrupted; future requests will reconnect.",
      ),
    );
  } else {
    const { DatabaseSync, backup } = require("node:sqlite");
    fs.mkdirSync(path.dirname(file), { recursive: true, mode: 0o700 });
    sqlite = new DatabaseSync(file);
    sqlite.exec(
      "PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON; PRAGMA busy_timeout = 5000;",
    );
    const columns = sqlite.prepare("PRAGMA table_info(messages)").all();
    if (columns.length && !columns.some((column) => column.name === "rowid")) {
      // Backup the old file, including WAL contents, before changing its schema.
      await backup(sqlite, `${file}.pre-v09-${Date.now()}.bak`);
    }
  }
  const query = async (sql, values = []) => {
    const connection = context.getStore();
    if (pool) return (connection || pool).query(postgresSql(sql), values);
    const execute = () => {
      const statement = sqlite.prepare(sql);
      if (statement.columns().length) return { rows: statement.all(...values) };
      const result = statement.run(...values);
      return { rows: [], rowCount: Number(result.changes) };
    };
    return connection ? execute() : serialize(execute);
  };
  const db = {
    kind,
    prepare(sql) {
      return {
        async all(...values) {
          return (await query(sql, values)).rows;
        },
        async get(...values) {
          return (await query(sql, values)).rows[0];
        },
        async run(...values) {
          return query(sql, values);
        },
      };
    },
    async exec(sql) {
      if (pool) return (context.getStore() || pool).query(postgresSql(sql));
      const execute = () => sqlite.exec(sql);
      return context.getStore() ? execute() : serialize(execute);
    },
    async transaction(callback) {
      if (context.getStore()) return callback(db);
      const execute = async () => {
        const connection = pool ? await pool.connect() : sqlite;
        try {
          return await context.run(connection, async () => {
            await db.exec(pool ? "BEGIN" : "BEGIN IMMEDIATE");
            try {
              const result = await callback(db);
              await db.exec("COMMIT");
              return result;
            } catch (error) {
              await db.exec("ROLLBACK");
              throw error;
            }
          });
        } finally {
          if (pool) connection.release();
        }
      };
      return pool ? execute() : serialize(execute);
    },
    async close() {
      if (pool) await pool.end();
      else {
        await queue;
        sqlite.close();
      }
    },
  };
  try {
    await db.transaction(async () => {
      if (pool) await db.prepare("SELECT pg_advisory_xact_lock(9170901)").get();
      await db.exec(
        sqlite
          ? schema.replace(
              /^CREATE INDEX IF NOT EXISTS messages_conversation_rowid_idx.*$/m,
              "",
            )
          : schema,
      );
      if (sqlite) {
        const userColumns = new Set(
          (await db.prepare("PRAGMA table_info(users)").all()).map(
            (column) => column.name,
          ),
        );
        for (const [name, type] of [
          ["bio", "TEXT NOT NULL DEFAULT ''"],
          ["avatar_mime", "TEXT NOT NULL DEFAULT ''"],
          ["avatar_blob", "BLOB"],
          ["avatar_updated_at", "TEXT NOT NULL DEFAULT ''"],
        ]) {
          if (!userColumns.has(name))
            await db.exec(`ALTER TABLE users ADD COLUMN ${name} ${type}`);
        }
        const memberColumns = await db
          .prepare("PRAGMA table_info(conversation_members)")
          .all();
        if (
          !memberColumns.some(
            (column) => column.name === "cleared_before_rowid",
          )
        ) {
          await db.exec(
            "ALTER TABLE conversation_members ADD COLUMN cleared_before_rowid INTEGER NOT NULL DEFAULT 0",
          );
        }
        const messageColumns = await db
          .prepare("PRAGMA table_info(messages)")
          .all();
        if (!messageColumns.some((column) => column.name === "rowid")) {
          await db.exec("ALTER TABLE messages RENAME TO messages_v08");
          await db.exec(schema);
          await db.exec(
            "INSERT INTO messages SELECT rowid, * FROM messages_v08",
          );
          await db.exec("DROP TABLE messages_v08");
          await db.exec(schema);
        }
        await db.exec(schema);
      }
      await reseedMessages(db);
    });
    return db;
  } catch (error) {
    await db.close();
    throw error;
  }
}

async function reseedMessages(db) {
  const max = await db
    .prepare(
      `SELECT MAX(value) AS value FROM (
    SELECT COALESCE(MAX(rowid), 0) AS value FROM messages
    UNION ALL SELECT COALESCE(MAX(cleared_before_rowid), 0) AS value FROM conversation_members
  ) AS counters`,
    )
    .get();
  const cutoff = Number(max.value || 0);
  if (db.kind === "postgres") {
    await db
      .prepare(
        "SELECT setval('messages_rowid_seq', GREATEST(?, (SELECT last_value FROM messages_rowid_seq), 1), true)",
      )
      .get(cutoff);
  } else {
    const entry = await db
      .prepare("SELECT seq FROM sqlite_sequence WHERE name = 'messages'")
      .get();
    if (!entry)
      await db
        .prepare(
          "INSERT INTO sqlite_sequence (name, seq) VALUES ('messages', ?)",
        )
        .run(cutoff);
    else if (Number(entry.seq) < cutoff)
      await db
        .prepare("UPDATE sqlite_sequence SET seq = ? WHERE name = 'messages'")
        .run(cutoff);
  }
}

module.exports = { openDatabase, reseedMessages, postgresSql, postgresConfig };
